### ISSUE TITLE
5.11.5 build

### ISSUE THREAD

**Issue by raybellwaves** [conda-forge/isort-feedstock#79]
### Comment:

A hotfix was released for version 5.11 (5.11.5): https://pypi.org/project/isort/5.11.5/ it would be good if that is also available via conda-forge.

I'm not familiar with a hotfix on conda-forge. I assume a PR has to made to build off a previous meta.yaml. Once that is merged meta.yaml can be reverted to the latest version and bumping the build number

**Comment by nehaljwani** [comment]
I've created a branch for 5.11.x and pushed your change there.
